### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by amusi** [MegEngine/MegEngine#10]
## 环境
1.系统环境：Ubuntu16.04
2.MegEngine版本：0.3.1
3.python版本：3.6

你好，我在用 MegEngine 写代码的时候遇到了一个 Bug。跑下面这段代码时，显存不断增加，感觉木有释放。Bug 代码如下：

```python3
import megengine as mge
import megengine.module as M
import numpy as np

class Net(M.Module):

    def __init__(self):
        self.fc0 = M.Linear(2, 100)

    def forward(self, inp):
        return self.fc0(inp)

net = Net()

for i in range(100000):
    data = mge.tensor(
        np.random.rand(64, 2).astype(np.float32) * 2 - 1
    )
    net(data)

```
这个 Bug 很奇怪，后来又反复看了几遍官网的教程和几个示例，我把下面这段代码放到循环外。

```python3
data = mge.tensor(
        np.random.rand(64, 2).astype(np.float32)
    )
```

然后在循环里使用 set_value 对 tensor 进行赋值才算解决显存问题。
```python3
import megengine as mge
import megengine.module as M
import numpy as np

class Net(M.Module):

    def __init__(self):
        self.fc0 = M.Linear(2, 100)

    def forward(self, inp):
        return self.fc0(inp)

net = Net()

data = mge.tensor(
        np.random.rand(64, 2).astype(np.float32)
    )

for i in range(100000):
    data.set_value(np.random.rand(64, 2) * 2 -1)
    # data.set_value(data * 2 - 1)
    net(data)
```

但还是不理解为什么无法直接在循环里使用 mge.tensor？而是一定要用 set_value？
希望官方能解答一下呀

**Comment by lcxywfe** [comment]
https://github.com/MegEngine/MegEngine/issues/5
看起来是alpha版本的已知问题

**Comment by megvii-mge** [comment]
感谢您对MegEngine的关注，该问题是本次版本的已知问题https://github.com/MegEngine/MegEngine/issues/5，该问题的深层次原因是动态图机制实现还比较原始，无法正确进行引用计数，导致显存无法释放。暂时的规避方式是您说的这样，通过 set_value 来复用 tensor。问题有详细的解决进展后我们会更新到该issue下面，也欢迎您参加天元开发者交流群1029741705，及时获得最新进展！

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. MAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member
