### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by llxxxll** [MegEngine/MegEngine#11]
## 环境
1.系统环境：Linux ubuntu_vb 4.15.0-91-generic #92-Ubuntu SMP x86_64
2.MegEngine版本：默认版本
3.python版本：python 3.6

## 复现步骤
安装过程参考：https://megengine.org.cn/doc/latest/index.html#installation
1.`pip3 install megengine -f https://megengine.org.cn/whl/mge.html`
2.`python3`
3.提示
```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import megengine as meg
This is an placeholder only, please install by 'pip3 install megengine -f https://megengine.org.cn/whl/mge.html'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.local/lib/python3.6/site-packages/megengine/__init__.py", line 3, in <module>
    raise ValueError("This is an placeholder only")
ValueError: This is an placeholder only
>>> 
```

**Comment by megvii-mge** [comment]
您好，请升级您的 pip 至 19.0 以上版本再试下

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. MAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by llxxxll** [comment]
fixed！Thanks~
