### ISSUE TITLE
MegHair miss project

### ISSUE THREAD

**Issue by kuonangzhe** [MegEngine/MegEngine#13]
## 文档链接
sdk/load-and-run/README.md

## 问题描述
L17 提到 MegHair/utils/debug/load_network_and_run.py 似乎是另一个project？这个脚本目前似乎还没有？

感谢！

**Comment by megvii-mge** [comment]
此处确实与我们的代码现状不一致，我们会在下一个版本修正，感谢您对 MegEngine 项目的关注！

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. MAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by xxr3376** [comment]
Fixed in 20450817da0f292ed115ed36a97f0b90867918b8
