### ISSUE TITLE
MegStudio 没有办法使用国外手机号注册

### ISSUE THREAD

**Issue by CollinsPeriodLee** [MegEngine/MegEngine#15]
Megstudio 现在是不支持国外手机号注册吗？

**Comment by tpoisonooo** [comment]
貌似都算不上问题... 使用的短信服务商不支持外国手机号。 mge/web 开发都做不了啥。

**Comment by megvii-mge** [comment]
您好，我们暂时仅支持国内的手机号，未来会提供更多地区的支持，感谢您对 MegEngine 项目的关注

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member
