### ISSUE TITLE
BUG Issue 训练时加入 dropout gpu内存不断增加

### ISSUE THREAD

**Issue by xiaosongshine** [MegEngine/MegEngine#16]
## 环境
1.系统环境：ubuntu 18.0.4
2.MegEngine版本：0.3.1
3.python版本：3.7.6

使用gpu训练mnist数据集 Lenet时，占用gpu内存不断增加，直至gpu内存溢出（4g内存，batch 128）

## 请提供关键的代码片段便于追查问题
示例训练代码 gpu训练mnist数据集 Lenet时 加入两层dropout

去除drop 不会出问题

```
class LeNet(M.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        # 单信道图片, 两层  5x5 卷积 + ReLU + 池化
        self.conv1 = M.Conv2d(1, 6, 5)
        self.relu1 = M.ReLU()
        self.pool1 = M.MaxPool2d(2, 2)
        self.conv2 = M.Conv2d(6, 16, 5)
        self.relu2 = M.ReLU()
        self.pool2 = M.MaxPool2d(2, 2)
        # 两层全连接 + ReLU
        self.fc1 = M.Linear(16 * 5 * 5, 120)
        self.relu3 = M.ReLU()
        self.drop1 = M.Dropout(0.5)
        self.fc2 = M.Linear(120, 84)
        self.relu4 = M.ReLU()
        self.drop2 = M.Dropout(0.5)
        # 分类器
        self.classifer = M.Linear(84, 10)

    def forward(self, x):
        x = self.pool1(self.relu1(self.conv1(x)))
        x = self.pool2(self.relu2(self.conv2(x)))
        # F.flatten 将原本形状为 (N, C, H, W) 的张量x从第一个维度（即C）开始拉平成一个维度，
        # 得到的新张量形状为 (N, C*H*W) 。 等价于 reshape 操作： x = x.reshape(x.shape[0], -1)
        x = F.flatten(x, 1)
        x = self.relu3(self.fc1(x))
        x = self.drop1(x)
        x = self.relu4(self.fc2(x))
        x = self.drop2(x)
        x = self.classifer(x)
        return x
```

## 请提供完整的日志及报错信息
egBrainError: MegBrain core throws exception: mgb::MegDNNError
curand call failed: status=102(CURAND_STATUS_ALLOCATION_FAILED) call=curandGenerateUniform(m_curand_handle.gen(), dst.ptr<dt_float32>(), dst.layout.total_nr_elems())

**Comment by megvii-mge** [comment]
您好，该问题是本次版本的已知问题 [#5](https://github.com/MegEngine/MegEngine/issues/5)，我们会尽快修复这个问题。您可以暂时使用静态图来进行训练，非常感谢您对 MegEngine 项目的关注：）

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member
