### ISSUE TITLE
Feature Request 天元之后有打算添加模型转为onnx或者openvino等推理框架么

### ISSUE THREAD

**Issue by Rainweic** [MegEngine/MegEngine#21]
天元之后有打算添加模型转为onnx或者openvino等推理框架么

## 背景

模型训练好后可能会使用openvino这样的边缘设备部署

**Comment by megvii-mge** [comment]
感谢您对 MegEngine 项目的关注，我们暂时没有提供 onnx 模型到 MegEngine 的转换，后续版本会添加不同平台之间的相互转换，也欢迎您参与到我们的开发中来，一起改进 MegEngine ：）

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by zxytim** [comment]
很希望有这个功能，这样能打通 pytorch 训练 --> pytorch 模型导出 onnx --> onnx 导入 megengine --> 部署 的道路

**Comment by xxr3376** [comment]
@zxytim 这并不是同一件事情，MegEngine to ONNX 会近期内提供；但 ONNX to MegEngine 是独立的另外一件事情，从一个图转换到动态代码将会是一件非常困难的事情：https://github.com/pytorch/pytorch/issues/21683

至于 ONNX to MegEngine 静态 graph，这个暂时不在开发计划内

**Comment by Yaoxingtian** [comment]
> MegEngine to ONNX 会近期内提供

2022年了还是没有提供。。。

**Comment by a419775258** [comment]
欢迎使用 https://github.com/MegEngine/mgeconvert
