### ISSUE TITLE
FileNotFoundError 'plasma_store'; AttributeError in <function _ParallelDataLoaderIter>

### ISSUE THREAD

**Issue by Rlee719** [MegEngine/MegEngine#22]
运行官方Models repo中的resnet/train.py代码实例时出现以下报错: 

## 环境
1.系统环境：Linux Mint 19.2
2.MegEngine版本：0.3.1
3.python版本：python 3.7.5
4.硬件: laptop, intel i5 + Nvidia 1050ti

## 复现步骤
1. 运行 https://github.com/MegEngine/Models/blob/master/official/vision/classification/resnet/train.py

## 完整的日志及报错信息

26 15:40:52 preparing dataset..
26 15:41:32 Epoch 0 LR 1.250e-02
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    main()
  File "train.py", line 93, in main
    worker(0, 1, args)
  File "train.py", line 209, in worker
    train_func, train_queue, optimizer, args, epoch=epoch
  File "train.py", line 239, in train
    for step, (image, label) in enumerate(data_queue):
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 122, in __iter__
    return _ParallelDataLoaderIter(self)
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 192, in __init__
    from ._queue import PlasmaShmQueue
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/_queue.py", line 39, in <module>
    MGE_PLASMA_STORE_MANAGER = _PlasmaStoreManager()
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/_queue.py", line 29, in __init__
    stderr=None if debug_flag else subprocess.DEVNULL,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'plasma_store': 'plasma_store'
Exception ignored in: <function _PlasmaStoreManager.__del__ at 0x7ff9d40363b0>
Traceback (most recent call last):
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/_queue.py", line 33, in __del__
    if self.plasma_store and self.plasma_store.returncode is None:
**AttributeError**: '_PlasmaStoreManager' object has no attribute 'plasma_store'
Exception ignored in: <function _ParallelDataLoaderIter.__del__ at 0x7ffa5988b290>
Traceback (most recent call last):
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 544, in __del__
    if self.__initialized:
**AttributeError**: '_ParallelDataLoaderIter' object has no attribute '_ParallelDataLoaderIter__initialized'

## 初步分析

报错1: FileNotFoundError: [Errno 2] No such file or directory: 'plasma_store': 'plasma_store'

报错2: AttributeError: '_ParallelDataLoaderIter' object has no attribute '_ParallelDataLoaderIter__initialized'

https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/python_module/megengine/data/dataloader.py#L170

dataloader.py中_ParallelDataLoaderIter类初始化__initialzed变量时并未在__init__()中进行属性赋
值，若
https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/python_module/megengine/data/dataloader.py#L233
不执行则导致报错2

**Comment by wjfwzzc** [comment]
请先在shell中尝试运行`plasma_store`，如果出现`-bash: plasma_store: command not found`，则说明pyarrow没有装好，请尝试删除pyarrow并重装：
```bash
pip3 uninstall pyarrow
pip3 install pyarrow
```

**Comment by wjfwzzc** [comment]
另`self.__initialzed`是一个typo，本来lint应该查出来的……感谢指出，我们会尽快修复。

**Comment by Rlee719** [comment]
> 请先在shell中尝试运行`plasma_store`，如果出现`-bash: plasma_store: command not found`，则说明pyarrow没有装好，请尝试删除pyarrow并重装：
> 
> ```shell
> pip3 uninstall pyarrow
> pip3 install pyarrow -U
> ```
> 
> 另外能否提供一下重装之前pyarrow的版本？我们想确认一下是否是版本问题。

重装前后版本均为0.16.0，重装后仍然报错，但注意到pip3提示
`
  WARNING: The script plasma_store is installed in '/home/rlee/.local/bin' which is not on PATH.
`
于是建立软连接
`
sudo ln -s /home/rlee/.local/bin/plasma_store /usr/bin/plasma_store
`
之后解决该报错，但运行时再次出现报错信息如下

26 17:35:50 preparing dataset..
26 17:36:14 Epoch 0 LR 1.250e-02
/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/mge_plasma_136f282090b11a1f, retrying 20 more times
/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/mge_plasma_136f282090b11a1f, retrying 19 more times
...
/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/mge_plasma_136f282090b11a1f, retrying 11 more times
/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/mge_plasma_136f282090b11a1f, retrying 10 more times
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    main()
  File "train.py", line 93, in main
    worker(0, 1, args)
  File "train.py", line 209, in worker
    train_func, train_queue, optimizer, args, epoch=epoch
  File "train.py", line 239, in train
    for step, (image, label) in enumerate(data_queue):
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 152, in __next__
    minibatch = self._get_next_batch()
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 512, in _get_next_batch
    batch_data = self._try_get_next_batch()
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/dataloader.py", line 503, in _try_get_next_batch
    return self.batch_queue.get(timeout=1)
  File "/home/rlee/.local/lib/python3.7/site-packages/megengine/data/_queue.py", line 77, in get
    self.client = plasma.connect(self.socket_name)
  File "pyarrow/_plasma.pyx", line 850, in pyarrow._plasma.connect
  File "pyarrow/_plasma.pyx", line 291, in pyarrow._plasma.plasma_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Could not connect to socket /tmp/mge_plasma_136f282090b11a1f
^C

所示的进程通信问题，目前仍未解决

**Comment by Rlee719** [comment]
> 另`self.__initialzed`是一个typo，本来lint应该查出来的……感谢指出，我们会尽快修复。

不用谢，辛苦了 :)

**Comment by wjfwzzc** [comment]
不建议用软链的方式解决，`PATH`中不存在`~/.local/bin`可能与您使用的系统有关系（我们目前只在Ubuntu下测试过）。

具体而言，我们怀疑您用sudo做了`plasm_store`的软链，可能产生了文件用户权限不match的问题。
您可以首先查看一下`/tmp/mge_plasma_136f282090b11a1f`是否属于root用户。
如果是的话，尝试一下用sudo运行`train.py`是否报错。
如果不再报错说明确实是文件用户权限的问题。

如果暂时无法解决该问题，可以考虑修改`Dataloader`的参数`num_workers=0`。会在一定程度上影响速度。

**Comment by Rlee719** [comment]
添加PATH并删除软链后/tmp下文件不再属于root用户，但原报错仍然出现，如截图中所示

![screenshot_7](https://user-images.githubusercontent.com/29767467/77644193-9f36bc80-6f9b-11ea-9901-92077571f808.png)
![screenshot_8](https://user-images.githubusercontent.com/29767467/77644211-a3fb7080-6f9b-11ea-83bf-d99e046ef3f7.png)

设定num_workers=0后可以运行。

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by MrsWhitney** [comment]
> 请先在shell中尝试运行`plasma_store`，如果出现`-bash: plasma_store: command not found`，则说明pyarrow没有装好，请尝试删除pyarrow并重装：
> 
> ```shell
> pip3 uninstall pyarrow
> pip3 install pyarrow -U
> ```
> 
> 另外能否提供一下重装之前pyarrow的版本？我们想确认一下是否是版本问题。
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by hukun-megvii** [comment]
> 添加PATH并删除软链后/tmp下文件不再属于root用户，但原报错仍然出现，如截图中所示

能否打开debug开关，观察一下log？即设置`num_workers > 0`后执行如下命令：

```bash
MGE_DATALOADER_PLASMA_DEBUG=1 python3 train.py --save=./data/models
```

**Comment by MegChai** [comment]
@Rlee719 你好，请尝试用 MegEngine v1.0.0 正式版跑 Models 中的 resnet/train.py ，应该不会有问题啦
