### ISSUE TITLE
请问后续是否会开源数据处理的相关项目？

### ISSUE THREAD

**Issue by liudonggang** [MegEngine/MegEngine#24]
## 请简要描述您的需求
 请问是否有开源数据处理方面的项目？

**Comment by megvii-mge** [comment]
您好，感谢您关注我们的 brain++ 生态，MegData 和 MegCopute 暂时没有开源计划，更多信息请您访问 https://www.brainpp.com/

**Comment by gujun720** [comment]
> ## 请简要描述您的需求
> 请问是否有开源数据处理方面的项目？

你是不是需要对模型生成的海量向量数据进行存储，并进行高性能的相似度搜索？
可以看看Milvus向量搜索引擎
https://github.com/milvus-io/milvus

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by xxr3376** [comment]
closed due to inactive.
