### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [MegEngine/MegEngine#26]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [FilterEngine](https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/dnn/src/common/cv/filter.cpp#L107 "Destructor for FilterEngine")
- [HalideExecutable::FunctionHandle](https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/src/jit/impl/halide/halide_executable.cpp#L28 "Destructor for HalideExecutable::FunctionHandle")

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by windreamer** [comment]
Hi @elfring,

Definitely!
Thank you for your kind suggestion.

**Comment by xxr3376** [comment]
Fixed in 32cd9ca0bd307eb5eb2153d64098e9d4fa495710.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/MegEngine/MegEngine/commit/32cd9ca0bd307eb5eb2153d64098e9d4fa495710 "Deletion of three redundant checks").
