### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by zhangheng408** [MegEngine/MegEngine#28]
## 环境
1.系统环境：Centos 7.4
2.MegEngine版本：0.3.1
3.python版本：3.6

## 复现步骤
1. cd official/vision/classification/resnet
2. 运行model中的resnet18或resnet50
python3 -u train.py --data /mnt/lustre/share/images --arch resnet18 --batch-size 32 --learning-rate 0.0125 --ngpus 8 --save .
3. 出现错误：ERR cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version (err 35)

## 请提供关键的代码片段便于追查问题
![image](https://user-images.githubusercontent.com/22138772/77674927-3ebd7480-6fc7-11ea-9971-61c0a285579a.png)
![image](https://user-images.githubusercontent.com/22138772/77674910-39602a00-6fc7-11ea-9836-fba931ef0c4c.png)

**Comment by zhangheng408** [comment]
已经正确设置LIBCUDA_PATH环境变量。是否是有其他选项或配置需要注意？

**Comment by zhangheng408** [comment]
而且正常情况下，第一次getLastError()之后，第二次getLastError()应该不会报错的。

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by zhangheng408** [comment]
我使用的环境是 CUDA 10.1.168 , driver 418.67,  V100显卡。满足官网所属环境要求

**Comment by megvii-mge** [comment]
感谢您对 MegEngine 项目的关注，您可以用 ldd 命令看一下 _internal 下的动态库 .so 文件指向的 cuda 路径

**Comment by windreamer** [comment]
@zhangheng408 如果您了解 LIBCUDA_PATH 环境变量，您应该是已经看过 cuda-stub 相关的代码

为了使得 MegEngine 可以正确的打包为 manylinux2010 标准的wheel包，同时不需要包含 libcuda.so 驱动，MegEngine 包含了一个 cuda-stub 的 so 用来将相关请求转发到系统的 libcuda.so 中

具体代码您可以参考: https://github.com/MegEngine/MegEngine/blob/master/dnn/cuda-stub/src/libcuda.cpp

所以你可以观察一下是否您的驱动(libcuda.so) 是在 LIBCUDA_PATH 的路径中，或者在 cuda-stub 可以找到的标准路径中

从目前的返回值（35）来看，cuda-stub是找到了一个 驱动，但是这个驱动过旧了，所以可能您需要检查是否正确配置了环境。

更多情况也希望您能补充更多日志来协助我们分析

**Comment by xxr3376** [comment]
closed due to inactive.
