### ISSUE TITLE
BUG Issue 不支持 int32 类型的矩阵乘

### ISSUE THREAD

**Issue by constroy** [MegEngine/MegEngine#29]
## 环境
1.系统环境：linux without cuda
2.MegEngine版本：0.3.1
3.python版本：3.8

## 复现步骤
1.
2.
3.

## 请提供关键的代码片段便于追查问题
```python
import megengine as mge
a = mge.ones((3, 4))
b = mge.ones((4, 5))
print(a @ b)
```

## 请提供完整的日志及报错信息
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/constroy/.local/lib/python3.8/site-packages/megengine/core/tensor.py", line 65, in wrapped
    return Tensor(f(self._attach(comp_graph), other))
  File "/home/constroy/.local/lib/python3.8/site-packages/megengine/_internal/mgb.py", line 1779, in __matmul__
    return matrix_mul(self, rhs)
  File "/home/constroy/.local/lib/python3.8/site-packages/megengine/_internal/opr.py", line 332, in matrix_mul
    outputs = _mgb._create_opr("MatrixMulV2", all_inputs, all_params, config)
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::MegDNNError
assertion `C.valid() && (C == C_candi || C == C_candi2)' failed at /home/code/dnn/src/common/matrix_mul.cpp:42: void megdnn::MatrixMulForward::deduce_dtype(megdnn::DType, megdnn::DType, megdnn::DType&)
extra message: unsupported MatMul(Int32, Int32) -> invalid
+ bt:/home/constroy/.local/lib/python3.8/site-packages/megengine/_internal/_mgb.cpython-38-x86_64-linux-gnu.so{1bf8371,1fa8fc4,1fa8ff2,1ff5a7c}
| Associated operator: id=25 name=matrix_mul(broadcast[4])[25] type=mgb::opr::MatrixMul
|   input variables: 
|     0: {id:5, layout:{3(4),4(1)}, Int32, owner:broadcast(1[0])[4]{Broadcast}, name:broadcast(1[0])[4], slot:0, cpu0:0, d, 2, 2}
|     1: {id:14, layout:{4(5),5(1)}, Int32, owner:broadcast(1[0])[13]{Broadcast}, name:broadcast(1[0])[13], slot:0, cpu0:0, d, 2, 2}
|   output variables: 
|     0: {id:26, shape:{}, invalid, owner:matrix_mul(broadcast[4])[25]{MatrixMul}, name:matrix_mul(broadcast[4])[25], slot:0, cpu0:0, d, 1, 1}
|     1: {id:27, shape:{}, Byte, owner:matrix_mul(broadcast[4])[25]{MatrixMul}, name:matrix_mul(broadcast[4])[25]:workspace, slot:1, cpu0:0, d, 1, 1}
```

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. TELEGRAM +4915219211439 Or EMAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by xiaocenxiaocen** [comment]
int32的矩阵乘法需要output是int64的数据类型，这样才能保证不会溢出。  
而且现在还没有int64的支持。可以用float32来做矩阵乘。
