### ISSUE TITLE
希望支持移动端边缘计算设备

### ISSUE THREAD

**Issue by ouening** [MegEngine/MegEngine#4]
## 背景

边缘计算可以保证数据的隐私和安全性，目前流行的树莓派、jetson nano等轻量化计算设备被广泛应用于执行深度学习任务。
## 需求描述

使用jetson nano设备紧源码编译megengine，遇到一些问题，最后发现应该是还不支持这种设备，准确来说是不支持jetson nano的GPU类型。
1) LLVM问题。
官网教程提示LLVM版本可以>=6.0，我根据https://apt.llvm.org/的方法使用apt安装LLVM9.0版本之后，cmake报错：
```
build ➤ cmake -DMGE_WITH_LLVM=OFF ..
FATALUnknown machine architecture for MegEngine.
-- Using GNU gold linker.
-- Setting build type to 'RelWithDebInfo' as none was specified.
CMake Error at cmake/Halide.cmake:2 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "6.0".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-9/cmake/LLVMConfig.cmake, version: 9.0.0

Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


-- Configuring incomplete, errors occurred!
```
行，那我就不使能JIT，使用cmake编译选项控制：`-DMGE_WITH_JIT=OFF`

2) CUDA arch问题
失能JIT镜像编译：
```bash
cmake -DMGE_WITH_JIT=OFF ..
```
得到下面错误：
```
CMake Error at CMakeLists.txt:231 (message):
  Unsupported CUDA host arch.
```
看错误应该是GPU架构不支持，通过pytorch查看GPU的算力是5.3

3) flat_buffer问题
失能GPU后继续cmake，出现错误：
```
CMake Error at src/CMakeLists.txt:118 (build_flatbuffers):
  Unknown CMake command "build_flatbuffers".
```
那就下载flatbuffers镜像编译安装：https://github.com/google/flatbuffers/releases

编译安装之后发现并没有`build_flatbuffers`这个执行文件，所以还是无法cmake构建项目。

能力有限，测试就到此为止了

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. MAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by xxr3376** [comment]
端侧设备的编译工具链正在准备中，5月内就会开源放出，你提到的这几个问题都进行了修复。（不过确实还没精力来管 jetson nano 的 GPU 的适配，会优先把 arm 相关的做了）

**Comment by xxr3376** [comment]
@ouening ARM 版本的部署能力已经提供了，具体可以参见：https://megengine.org.cn/doc/latest/inference_example/inference_chinese.html


Jetson nano 的 GPU 适配工作暂时无人力支持。

**Comment by haolongzhangm** [comment]
由于一些原因， jetson nano目前支持在 jetson  板子里面的环境就行构建， 但是不支持linux-cross-jetson 构建，未来会优化一下

**Comment by MegChai** [comment]
@ouening 你好，请问是否有尝试在  jetson 板子里 build 最新版本的 MegEngine 呢？

**Comment by ouening** [comment]
抱歉，最近都没玩jetson nano了，等有空再研究

**Comment by MegChai** [comment]
> 抱歉，最近都没玩jetson nano了，等有空再研究

好的，随时欢迎您向我们反馈 MegEgnine 的使用体验 =w=

由于这个 Feature 已经支持了，该 Issue 将被关闭，如果有新的问题可以另外发 Issue~
