### ISSUE TITLE
动态模式显存占用和性能尚待进一步优化LIST

### ISSUE THREAD

**Issue by megvii-mge** [MegEngine/MegEngine#5]
动态图模式下存在以下问题，我们将持续优化：

- 当前实现导致动态创建的 Tensor 显存不能自动回收，目前需要使用 set_value() 方法手动复用 Tensor 来避免显存持续增加
- 动态模式下的显存占用较高
- PyTorch 子图，megengine.Funtion 等算子占用显存会持续增加
- random operator 以及依赖它的 operator 暂时无法去重，导致显存使用持续增加，例如 dropout

**Comment by MrsWhitney** [comment]
TESTIMONY ON HOW I BECAME INSTANT MILLIONAIRE WITH THE HELP OF THE ILLUMINATI. MAIL THE COUNCIL AT ( illuminatiofficialverified.org@gmail.com )
Hello everyone, i have to write this testimony because of people out there who also will like to join the Illuminati, because i am really happy to be member of Illuminati cult society today, i have been searching for the right hand to join this organization of Illuminati i finally got this nice Prof.Monday and Barr. Mikhail ,who help me in joining even when i was asked to buy all the items my self which i did for the initiation. though it cost me some money, but every thing went out successfully, and an instant sum of 1,000,000,000.00 US dollars was given to me with a free home of my choice in CALIFORNIA USA. And also, power, influence, good position fame including $300,000,000.00 dollars monthly as a salary for me. If you are interested contact the Illuminati full membership council through this email address above . Today my family and i are  happy for following the Light. See you there. You may WHATSAPP CHAT HELPING MEMBERS  at +13252429274 for special information on how to be a full member

**Comment by xxr3376** [comment]
下列内容已经在 v1.0.0rc1 中完成修复
* 当前实现导致动态创建的 Tensor 显存不能自动回收，目前需要使用 set_value() 方法手动复用 Tensor 来避免显存持续增加
* 动态模式下的显存占用较高
* random operator 以及依赖它的 operator 暂时无法去重，导致显存使用持续增加，例如 dropout
