### ISSUE TITLE
Clarification on layouts

### ISSUE THREAD

**Issue by danpovey** [MegEngine/MegEngine#55]
It would be nice to clarify what the (device-independent) constraints are for tensor layouts:
E.g.:
  - Are negative strides allowed?
  - May the stride for any axis be zero ?
  - Is it possible for the strides to be such that they create 'aliasing' of elements?  E.g. num_rows == num_cols == 3, row_stride == col_stride == 1.

I also notice that you don't support tensors with no axes (i.e. you require ndim > 0)... I thought that was quite a nice feature of PyTorch, as there are some operations like summing over an axis which naturally reduce the num-axes by one.  Is there a reason you don't support that?

https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/dnn/include/megdnn/basic_types.h#L214

**Comment by xxr3376** [comment]
- Yes, negative strides are allowed. Tensors with negative strides may re-layout before the computation to meet contiguous requirements of some optimized kernel.
- zero stride are broadly used to broadcast some dimensions of a tensor. 
- It's possible to create 'aliasing' in your case.

For more detail about tensor layouts, you can refer to the implementation of iterating a tensor: https://github.com/MegEngine/MegEngine/blob/master/dnn/include/megdnn/tensor_iter.h#L121


Sadly we don't support tensor with no axes yet, this mainly because we define [`tensor.ndim=0` as an uninitialized shape](https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/dnn/include/megdnn/basic_types.h#L90) at the very beginning of this project, and it's hard to support this without changing old API behavior in past 5 years. (e.g. sum(x) returns a tensor which shape is [1]; `is_scalar` will return True for these tensor). 

Megengine is the brand new API based on our old core engine, it's possible to support this with huge changes. We are discussing this, any suggestions are welcome.

**Comment by ChaiMind** [comment]
This issue will be closed now and you can reopen it if you have any other questions.
